#-------------------Config port
#server.port=9090
spring:
  server:
    port: 9090

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect

  jsf:
    primefaces:
      FONT_AWESOME: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1081804428919463
            client-secret: 6d554f4c4e437bf4f1cac0100e845c3e
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
             userInfoUri: https://graph.facebook.com/me

          google:
            client-id: 929614887854-g6a7npugph3mapoav6upomh7tcem1br9.apps.googleusercontent.com
            client-secret: 1OV17hQXHsSDm9ylNG3HfNvb
            scope:
              - email
              - profile

          github:
            clientId: eabff59d830b9dbd4a68
            clientSecret: ee36adaafd79dbe58019d912cf3fcda36dc59f95
            scope:
              - user:email
              - read:user
#-------------------Upload File
#spring.servlet.multipart.max-file-size=128KB
#spring.servlet.multipart.max-request-size=128KB
#-------------------Postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=123456
#-------------------JPA
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
#-------------------Custom Error
#server.error.whitelabel.enabled=false
#server.error.path=/error
#--------------Facebook
#spring.security.oauth2.client.registration.facebook.client-id=
#spring.security.oauth2.client.registration.facebook.client-secret=
